name: Release Drafter
on:
  push:
    branches:
      - master
jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        name: Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   build:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: borales/actions-yarn@v2.3.0
#         with:
#           cmd: install
#       - uses: borales/actions-yarn@v2.3.0
#         with:
#           cmd: build
#       - uses: actions/create-release@latest
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           with:
#             tag_name: test
#             release_name: release
#             body: content
#             draft: false
#             prerelease: false
