name: Create Release
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: out/
      - uses: actions/download-artifact@v2
        with:
          name: site-build
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip
  release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project
